name: Publish CUPS Docker Image

on:
  push:
    paths:
      - 'Dockerfile'
      - 'etc-cups/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push (Ubuntu)
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          build-args: BASE_DISTRO=ubuntu:focal
          tags: |
            xjasonlyu/cups:latest
            xjasonlyu/cups:ubuntu

      - name: Build and Push (Debian)
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          build-args: BASE_DISTRO=debian:buster-slim
          tags: |
            xjasonlyu/cups:debian
